// Generated reference data: one row per local authority currently present in the
// Establishment table (isActive: true), with a pre-computed slug for /area/[slug] routes.
// Regenerate by re-running the query in this file's history (see git log) if the FSA
// feed ever adds/renames/removes a local authority — this is static rather than queried
// live so slug <-> name resolution doesn't need a DISTINCT scan over the whole table on
// every request, and so /area/page.tsx can list every area without an extra query.
//
// Local authorities with fewer than 50 active establishments are omitted — a handful
// of near-empty entries in the FSA feed (e.g. port authorities) aren't worth a landing page.

export interface LocalAuthority {
  name: string;
  slug: string;
  count: number;
}

export const LOCAL_AUTHORITIES: LocalAuthority[] = [
  { name: "Aberdeen City", slug: "aberdeen-city", count: 2202 },
  { name: "Aberdeenshire", slug: "aberdeenshire", count: 2783 },
  { name: "Adur", slug: "adur", count: 463 },
  { name: "Amber Valley", slug: "amber-valley", count: 1078 },
  { name: "Anglesey", slug: "anglesey", count: 763 },
  { name: "Angus", slug: "angus", count: 1042 },
  { name: "Antrim and Newtownabbey", slug: "antrim-and-newtownabbey", count: 1099 },
  { name: "Ards and North Down", slug: "ards-and-north-down", count: 1289 },
  { name: "Argyll and Bute", slug: "argyll-and-bute", count: 1279 },
  { name: "Armagh City, Banbridge and Craigavon", slug: "armagh-city-banbridge-and-craigavon", count: 1883 },
  { name: "Arun", slug: "arun", count: 1350 },
  { name: "Ashfield", slug: "ashfield", count: 966 },
  { name: "Ashford", slug: "ashford", count: 1255 },
  { name: "Babergh", slug: "babergh", count: 888 },
  { name: "Barking and Dagenham", slug: "barking-and-dagenham", count: 1459 },
  { name: "Barnet", slug: "barnet", count: 2882 },
  { name: "Barnsley", slug: "barnsley", count: 1890 },
  { name: "Basildon", slug: "basildon", count: 1406 },
  { name: "Basingstoke and Deane", slug: "basingstoke-and-deane", count: 1295 },
  { name: "Bassetlaw", slug: "bassetlaw", count: 1097 },
  { name: "Bath and North East Somerset", slug: "bath-and-north-east-somerset", count: 1847 },
  { name: "Bedford", slug: "bedford", count: 1654 },
  { name: "Belfast City", slug: "belfast-city", count: 3178 },
  { name: "Bexley", slug: "bexley", count: 1770 },
  { name: "Birmingham", slug: "birmingham", count: 10123 },
  { name: "Blaby", slug: "blaby", count: 674 },
  { name: "Blackburn", slug: "blackburn", count: 1313 },
  { name: "Blackpool", slug: "blackpool", count: 1683 },
  { name: "Blaenau Gwent", slug: "blaenau-gwent", count: 670 },
  { name: "Bolsover", slug: "bolsover", count: 741 },
  { name: "Bolton", slug: "bolton", count: 2415 },
  { name: "Boston", slug: "boston", count: 639 },
  { name: "Bournemouth, Christchurch and Poole", slug: "bournemouth-christchurch-and-poole", count: 3523 },
  { name: "Bracknell Forest", slug: "bracknell-forest", count: 796 },
  { name: "Bradford", slug: "bradford", count: 4659 },
  { name: "Braintree", slug: "braintree", count: 1274 },
  { name: "Breckland", slug: "breckland", count: 1261 },
  { name: "Brent", slug: "brent", count: 2493 },
  { name: "Brentwood", slug: "brentwood", count: 754 },
  { name: "Bridgend", slug: "bridgend", count: 1366 },
  { name: "Brighton and Hove", slug: "brighton-and-hove", count: 3001 },
  { name: "Bristol", slug: "bristol", count: 4482 },
  { name: "Broadland", slug: "broadland", count: 959 },
  { name: "Bromley", slug: "bromley", count: 2475 },
  { name: "Bromsgrove", slug: "bromsgrove", count: 745 },
  { name: "Broxbourne", slug: "broxbourne", count: 868 },
  { name: "Broxtowe", slug: "broxtowe", count: 816 },
  { name: "Buckinghamshire", slug: "buckinghamshire", count: 4585 },
  { name: "Burnley", slug: "burnley", count: 880 },
  { name: "Bury", slug: "bury", count: 1226 },
  { name: "Caerphilly", slug: "caerphilly", count: 1553 },
  { name: "Calderdale", slug: "calderdale", count: 1902 },
  { name: "Cambridge City", slug: "cambridge-city", count: 1487 },
  { name: "Camden", slug: "camden", count: 4260 },
  { name: "Cannock Chase", slug: "cannock-chase", count: 831 },
  { name: "Canterbury City", slug: "canterbury-city", count: 1648 },
  { name: "Cardiff", slug: "cardiff", count: 3481 },
  { name: "Carmarthenshire", slug: "carmarthenshire", count: 2177 },
  { name: "Castle Point", slug: "castle-point", count: 537 },
  { name: "Causeway Coast and Glens", slug: "causeway-coast-and-glens", count: 1468 },
  { name: "Central Bedfordshire", slug: "central-bedfordshire", count: 1712 },
  { name: "Ceredigion", slug: "ceredigion", count: 1086 },
  { name: "Charnwood", slug: "charnwood", count: 1488 },
  { name: "Chelmsford", slug: "chelmsford", count: 1603 },
  { name: "Cheltenham", slug: "cheltenham", count: 1079 },
  { name: "Cherwell", slug: "cherwell", count: 1331 },
  { name: "Cheshire East", slug: "cheshire-east", count: 3104 },
  { name: "Cheshire West and Chester", slug: "cheshire-west-and-chester", count: 2956 },
  { name: "Chesterfield", slug: "chesterfield", count: 955 },
  { name: "Chichester", slug: "chichester", count: 1441 },
  { name: "Chorley", slug: "chorley", count: 989 },
  { name: "City of London Corporation", slug: "city-of-london-corporation", count: 1846 },
  { name: "Clackmannanshire", slug: "clackmannanshire", count: 503 },
  { name: "Colchester", slug: "colchester", count: 1641 },
  { name: "Comhairle nan Eilean Siar (Western Isles)", slug: "comhairle-nan-eilean-siar-western-isles", count: 575 },
  { name: "Conwy", slug: "conwy", count: 1605 },
  { name: "Cornwall", slug: "cornwall", count: 5394 },
  { name: "Cotswold", slug: "cotswold", count: 1098 },
  { name: "Coventry", slug: "coventry", count: 3101 },
  { name: "Crawley", slug: "crawley", count: 965 },
  { name: "Croydon", slug: "croydon", count: 3159 },
  { name: "Cumberland", slug: "cumberland", count: 2767 },
  { name: "Dacorum", slug: "dacorum", count: 1291 },
  { name: "Darlington", slug: "darlington", count: 915 },
  { name: "Dartford", slug: "dartford", count: 1082 },
  { name: "Denbighshire", slug: "denbighshire", count: 1156 },
  { name: "Derby City", slug: "derby-city", count: 2284 },
  { name: "Derbyshire Dales", slug: "derbyshire-dales", count: 913 },
  { name: "Derry City and Strabane", slug: "derry-city-and-strabane", count: 1356 },
  { name: "Doncaster", slug: "doncaster", count: 2807 },
  { name: "Dorset", slug: "dorset", count: 5147 },
  { name: "Dover", slug: "dover", count: 1206 },
  { name: "Dudley", slug: "dudley", count: 2673 },
  { name: "Dumfries and Galloway", slug: "dumfries-and-galloway", count: 2719 },
  { name: "Dundee City", slug: "dundee-city", count: 1407 },
  { name: "Durham", slug: "durham", count: 4631 },
  { name: "Ealing", slug: "ealing", count: 3733 },
  { name: "East Ayrshire", slug: "east-ayrshire", count: 1154 },
  { name: "East Cambridgeshire", slug: "east-cambridgeshire", count: 790 },
  { name: "East Devon", slug: "east-devon", count: 1548 },
  { name: "East Dunbartonshire", slug: "east-dunbartonshire", count: 704 },
  { name: "East Hampshire", slug: "east-hampshire", count: 1094 },
  { name: "East Hertfordshire", slug: "east-hertfordshire", count: 1401 },
  { name: "East Lindsey", slug: "east-lindsey", count: 2300 },
  { name: "East Lothian", slug: "east-lothian", count: 886 },
  { name: "East Renfrewshire", slug: "east-renfrewshire", count: 646 },
  { name: "East Riding of Yorkshire", slug: "east-riding-of-yorkshire", count: 3172 },
  { name: "East Staffordshire", slug: "east-staffordshire", count: 1204 },
  { name: "East Suffolk", slug: "east-suffolk", count: 2512 },
  { name: "Eastbourne", slug: "eastbourne", count: 1037 },
  { name: "Eastleigh", slug: "eastleigh", count: 977 },
  { name: "Edinburgh (City of)", slug: "edinburgh-city-of", count: 5123 },
  { name: "Elmbridge", slug: "elmbridge", count: 1114 },
  { name: "Enfield", slug: "enfield", count: 2393 },
  { name: "Epping Forest", slug: "epping-forest", count: 1042 },
  { name: "Epsom and Ewell", slug: "epsom-and-ewell", count: 561 },
  { name: "Erewash", slug: "erewash", count: 944 },
  { name: "Exeter City", slug: "exeter-city", count: 1117 },
  { name: "Falkirk", slug: "falkirk", count: 1216 },
  { name: "Fareham", slug: "fareham", count: 799 },
  { name: "Fenland", slug: "fenland", count: 715 },
  { name: "Fermanagh and Omagh", slug: "fermanagh-and-omagh", count: 1445 },
  { name: "Fife", slug: "fife", count: 5040 },
  { name: "Flintshire", slug: "flintshire", count: 1307 },
  { name: "Folkestone and Hythe", slug: "folkestone-and-hythe", count: 1302 },
  { name: "Forest of Dean", slug: "forest-of-dean", count: 807 },
  { name: "Fylde", slug: "fylde", count: 844 },
  { name: "Gateshead", slug: "gateshead", count: 1646 },
  { name: "Gedling", slug: "gedling", count: 833 },
  { name: "Glasgow City", slug: "glasgow-city", count: 6614 },
  { name: "Gloucester City", slug: "gloucester-city", count: 1072 },
  { name: "Gosport", slug: "gosport", count: 608 },
  { name: "Gravesham", slug: "gravesham", count: 826 },
  { name: "Great Yarmouth", slug: "great-yarmouth", count: 1098 },
  { name: "Greenwich", slug: "greenwich", count: 2391 },
  { name: "Guildford", slug: "guildford", count: 1144 },
  { name: "Gwynedd", slug: "gwynedd", count: 2104 },
  { name: "Hackney", slug: "hackney", count: 2448 },
  { name: "Halton", slug: "halton", count: 903 },
  { name: "Hammersmith and Fulham", slug: "hammersmith-and-fulham", count: 2016 },
  { name: "Harborough", slug: "harborough", count: 774 },
  { name: "Haringey", slug: "haringey", count: 1948 },
  { name: "Harlow", slug: "harlow", count: 685 },
  { name: "Harrow", slug: "harrow", count: 1903 },
  { name: "Hart", slug: "hart", count: 634 },
  { name: "Hartlepool", slug: "hartlepool", count: 770 },
  { name: "Hastings", slug: "hastings", count: 911 },
  { name: "Havant", slug: "havant", count: 1062 },
  { name: "Havering", slug: "havering", count: 2021 },
  { name: "Herefordshire", slug: "herefordshire", count: 1779 },
  { name: "Hertsmere", slug: "hertsmere", count: 841 },
  { name: "High Peak", slug: "high-peak", count: 902 },
  { name: "Highland", slug: "highland", count: 6009 },
  { name: "Hillingdon", slug: "hillingdon", count: 2237 },
  { name: "Hinckley and Bosworth", slug: "hinckley-and-bosworth", count: 919 },
  { name: "Horsham", slug: "horsham", count: 1332 },
  { name: "Hounslow", slug: "hounslow", count: 2337 },
  { name: "Hull City", slug: "hull-city", count: 2287 },
  { name: "Huntingdonshire", slug: "huntingdonshire", count: 1527 },
  { name: "Hyndburn", slug: "hyndburn", count: 760 },
  { name: "Inverclyde", slug: "inverclyde", count: 635 },
  { name: "Ipswich", slug: "ipswich", count: 1118 },
  { name: "Isle of Wight", slug: "isle-of-wight", count: 1701 },
  { name: "Isles of Scilly", slug: "isles-of-scilly", count: 132 },
  { name: "Islington", slug: "islington", count: 2591 },
  { name: "Kensington and Chelsea", slug: "kensington-and-chelsea", count: 1998 },
  { name: "King's Lynn and West Norfolk", slug: "king-s-lynn-and-west-norfolk", count: 1505 },
  { name: "Kingston-Upon-Thames", slug: "kingston-upon-thames", count: 1436 },
  { name: "Kirklees", slug: "kirklees", count: 3855 },
  { name: "Knowsley", slug: "knowsley", count: 819 },
  { name: "Lambeth", slug: "lambeth", count: 2644 },
  { name: "Lancaster City", slug: "lancaster-city", count: 1173 },
  { name: "Leeds", slug: "leeds", count: 7410 },
  { name: "Leicester City", slug: "leicester-city", count: 3369 },
  { name: "Lewes", slug: "lewes", count: 943 },
  { name: "Lewisham", slug: "lewisham", count: 2482 },
  { name: "Lichfield", slug: "lichfield", count: 887 },
  { name: "Lincoln City", slug: "lincoln-city", count: 1118 },
  { name: "Lisburn and Castlereagh City", slug: "lisburn-and-castlereagh-city", count: 1007 },
  { name: "Liverpool", slug: "liverpool", count: 4577 },
  { name: "Luton", slug: "luton", count: 1692 },
  { name: "Maidstone", slug: "maidstone", count: 1450 },
  { name: "Maldon", slug: "maldon", count: 683 },
  { name: "Malvern Hills", slug: "malvern-hills", count: 718 },
  { name: "Manchester", slug: "manchester", count: 6422 },
  { name: "Mansfield", slug: "mansfield", count: 894 },
  { name: "Medway", slug: "medway", count: 2130 },
  { name: "Melton", slug: "melton", count: 537 },
  { name: "Merthyr Tydfil", slug: "merthyr-tydfil", count: 584 },
  { name: "Merton", slug: "merton", count: 1566 },
  { name: "Mid and East Antrim", slug: "mid-and-east-antrim", count: 1159 },
  { name: "Mid Devon", slug: "mid-devon", count: 787 },
  { name: "Mid Suffolk", slug: "mid-suffolk", count: 859 },
  { name: "Mid Sussex", slug: "mid-sussex", count: 1340 },
  { name: "Mid Ulster", slug: "mid-ulster", count: 1370 },
  { name: "Middlesbrough", slug: "middlesbrough", count: 1161 },
  { name: "Midlothian", slug: "midlothian", count: 675 },
  { name: "Milton Keynes", slug: "milton-keynes", count: 2513 },
  { name: "Mole Valley", slug: "mole-valley", count: 781 },
  { name: "Monmouthshire", slug: "monmouthshire", count: 1105 },
  { name: "Moray", slug: "moray", count: 1132 },
  { name: "Neath Port Talbot", slug: "neath-port-talbot", count: 1193 },
  { name: "New Forest", slug: "new-forest", count: 1582 },
  { name: "Newark and Sherwood", slug: "newark-and-sherwood", count: 1151 },
  { name: "Newcastle Upon Tyne", slug: "newcastle-upon-tyne", count: 2705 },
  { name: "Newcastle-Under-Lyme", slug: "newcastle-under-lyme", count: 978 },
  { name: "Newham", slug: "newham", count: 2659 },
  { name: "Newport", slug: "newport", count: 1362 },
  { name: "Newry, Mourne and Down", slug: "newry-mourne-and-down", count: 1726 },
  { name: "North Ayrshire", slug: "north-ayrshire", count: 1378 },
  { name: "North Devon", slug: "north-devon", count: 1482 },
  { name: "North East Derbyshire", slug: "north-east-derbyshire", count: 814 },
  { name: "North East Lincolnshire", slug: "north-east-lincolnshire", count: 1724 },
  { name: "North Hertfordshire", slug: "north-hertfordshire", count: 1127 },
  { name: "North Kesteven", slug: "north-kesteven", count: 972 },
  { name: "North Lanarkshire", slug: "north-lanarkshire", count: 2636 },
  { name: "North Lincolnshire", slug: "north-lincolnshire", count: 1478 },
  { name: "North Norfolk", slug: "north-norfolk", count: 1509 },
  { name: "North Northamptonshire", slug: "north-northamptonshire", count: 3059 },
  { name: "North Somerset", slug: "north-somerset", count: 1708 },
  { name: "North Tyneside", slug: "north-tyneside", count: 1499 },
  { name: "North Warwickshire", slug: "north-warwickshire", count: 670 },
  { name: "North West Leicestershire", slug: "north-west-leicestershire", count: 959 },
  { name: "North Yorkshire", slug: "north-yorkshire", count: 7108 },
  { name: "Northumberland", slug: "northumberland", count: 3512 },
  { name: "Norwich City", slug: "norwich-city", count: 1573 },
  { name: "Nottingham City", slug: "nottingham-city", count: 3037 },
  { name: "Nuneaton and Bedworth", slug: "nuneaton-and-bedworth", count: 919 },
  { name: "Oadby and Wigston", slug: "oadby-and-wigston", count: 407 },
  { name: "Oldham", slug: "oldham", count: 1922 },
  { name: "Orkney Islands", slug: "orkney-islands", count: 461 },
  { name: "Oxford City", slug: "oxford-city", count: 1546 },
  { name: "Pembrokeshire", slug: "pembrokeshire", count: 2281 },
  { name: "Pendle", slug: "pendle", count: 805 },
  { name: "Perth and Kinross", slug: "perth-and-kinross", count: 1990 },
  { name: "Peterborough City", slug: "peterborough-city", count: 1999 },
  { name: "Plymouth City", slug: "plymouth-city", count: 1779 },
  { name: "Portsmouth", slug: "portsmouth", count: 1800 },
  { name: "Powys", slug: "powys", count: 2618 },
  { name: "Preston", slug: "preston", count: 1628 },
  { name: "Reading", slug: "reading", count: 1503 },
  { name: "Redbridge", slug: "redbridge", count: 2158 },
  { name: "Redcar and Cleveland", slug: "redcar-and-cleveland", count: 1231 },
  { name: "Redditch", slug: "redditch", count: 482 },
  { name: "Reigate and Banstead", slug: "reigate-and-banstead", count: 1104 },
  { name: "Renfrewshire", slug: "renfrewshire", count: 1502 },
  { name: "Rhondda Cynon Taf", slug: "rhondda-cynon-taf", count: 2026 },
  { name: "Ribble Valley", slug: "ribble-valley", count: 651 },
  { name: "Richmond-Upon-Thames", slug: "richmond-upon-thames", count: 1578 },
  { name: "Rochdale", slug: "rochdale", count: 1900 },
  { name: "Rochford", slug: "rochford", count: 666 },
  { name: "Rossendale", slug: "rossendale", count: 690 },
  { name: "Rother", slug: "rother", count: 1025 },
  { name: "Rotherham", slug: "rotherham", count: 2205 },
  { name: "Rugby", slug: "rugby", count: 928 },
  { name: "Runnymede", slug: "runnymede", count: 702 },
  { name: "Rushcliffe", slug: "rushcliffe", count: 922 },
  { name: "Rushmoor", slug: "rushmoor", count: 706 },
  { name: "Rutland", slug: "rutland", count: 460 },
  { name: "Salford", slug: "salford", count: 2090 },
  { name: "Sandwell", slug: "sandwell", count: 2712 },
  { name: "Scottish Borders", slug: "scottish-borders", count: 1640 },
  { name: "Sefton", slug: "sefton", count: 2392 },
  { name: "Sevenoaks", slug: "sevenoaks", count: 950 },
  { name: "Sheffield", slug: "sheffield", count: 4879 },
  { name: "Shetland Islands", slug: "shetland-islands", count: 281 },
  { name: "Shropshire", slug: "shropshire", count: 3124 },
  { name: "Slough", slug: "slough", count: 1017 },
  { name: "Solihull", slug: "solihull", count: 1402 },
  { name: "Somerset", slug: "somerset", count: 6080 },
  { name: "South Ayrshire", slug: "south-ayrshire", count: 1038 },
  { name: "South Cambridgeshire", slug: "south-cambridgeshire", count: 1317 },
  { name: "South Derbyshire", slug: "south-derbyshire", count: 885 },
  { name: "South Gloucestershire", slug: "south-gloucestershire", count: 2122 },
  { name: "South Hams", slug: "south-hams", count: 1100 },
  { name: "South Holland", slug: "south-holland", count: 798 },
  { name: "South Kesteven", slug: "south-kesteven", count: 1184 },
  { name: "South Lanarkshire", slug: "south-lanarkshire", count: 2476 },
  { name: "South Norfolk", slug: "south-norfolk", count: 1114 },
  { name: "South Oxfordshire", slug: "south-oxfordshire", count: 1261 },
  { name: "South Ribble", slug: "south-ribble", count: 832 },
  { name: "South Staffordshire", slug: "south-staffordshire", count: 744 },
  { name: "South Tyneside", slug: "south-tyneside", count: 1039 },
  { name: "Southampton", slug: "southampton", count: 1712 },
  { name: "Southend-On-Sea", slug: "southend-on-sea", count: 1480 },
  { name: "Southwark", slug: "southwark", count: 3299 },
  { name: "Spelthorne", slug: "spelthorne", count: 777 },
  { name: "St Albans City", slug: "st-albans-city", count: 1162 },
  { name: "St Helens", slug: "st-helens", count: 1371 },
  { name: "Stafford", slug: "stafford", count: 1121 },
  { name: "Staffordshire Moorlands", slug: "staffordshire-moorlands", count: 857 },
  { name: "Stevenage", slug: "stevenage", count: 691 },
  { name: "Stirling", slug: "stirling", count: 1254 },
  { name: "Stockport", slug: "stockport", count: 2736 },
  { name: "Stockton On Tees", slug: "stockton-on-tees", count: 1578 },
  { name: "Stoke-On-Trent", slug: "stoke-on-trent", count: 2238 },
  { name: "Stratford-on-Avon", slug: "stratford-on-avon", count: 1377 },
  { name: "Stroud", slug: "stroud", count: 1081 },
  { name: "Sunderland", slug: "sunderland", count: 2322 },
  { name: "Surrey Heath", slug: "surrey-heath", count: 688 },
  { name: "Sutton", slug: "sutton", count: 1329 },
  { name: "Swale", slug: "swale", count: 1227 },
  { name: "Swansea", slug: "swansea", count: 2442 },
  { name: "Swindon", slug: "swindon", count: 1656 },
  { name: "Tameside", slug: "tameside", count: 1686 },
  { name: "Tamworth", slug: "tamworth", count: 558 },
  { name: "Tandridge", slug: "tandridge", count: 696 },
  { name: "Teignbridge", slug: "teignbridge", count: 1320 },
  { name: "Telford and Wrekin Council", slug: "telford-and-wrekin-council", count: 1491 },
  { name: "Tendring", slug: "tendring", count: 1302 },
  { name: "Test Valley", slug: "test-valley", count: 1070 },
  { name: "Tewkesbury", slug: "tewkesbury", count: 801 },
  { name: "Thanet", slug: "thanet", count: 1520 },
  { name: "Three Rivers", slug: "three-rivers", count: 651 },
  { name: "Thurrock", slug: "thurrock", count: 1321 },
  { name: "Tonbridge and Malling", slug: "tonbridge-and-malling", count: 1055 },
  { name: "Torbay", slug: "torbay", count: 1516 },
  { name: "Torfaen", slug: "torfaen", count: 784 },
  { name: "Torridge", slug: "torridge", count: 768 },
  { name: "Tower Hamlets", slug: "tower-hamlets", count: 3172 },
  { name: "Trafford", slug: "trafford", count: 2202 },
  { name: "Tunbridge Wells", slug: "tunbridge-wells", count: 1079 },
  { name: "Uttlesford", slug: "uttlesford", count: 801 },
  { name: "Vale of Glamorgan", slug: "vale-of-glamorgan", count: 1321 },
  { name: "Vale of White Horse", slug: "vale-of-white-horse", count: 1044 },
  { name: "Wakefield", slug: "wakefield", count: 3064 },
  { name: "Walsall", slug: "walsall", count: 2183 },
  { name: "Waltham Forest", slug: "waltham-forest", count: 1978 },
  { name: "Wandsworth", slug: "wandsworth", count: 2897 },
  { name: "Warrington", slug: "warrington", count: 1715 },
  { name: "Warwick", slug: "warwick", count: 1397 },
  { name: "Watford", slug: "watford", count: 1024 },
  { name: "Waverley", slug: "waverley", count: 1064 },
  { name: "Wealden", slug: "wealden", count: 1375 },
  { name: "Welwyn Hatfield", slug: "welwyn-hatfield", count: 762 },
  { name: "West Berkshire", slug: "west-berkshire", count: 1274 },
  { name: "West Devon", slug: "west-devon", count: 628 },
  { name: "West Dunbartonshire", slug: "west-dunbartonshire", count: 722 },
  { name: "West Lancashire", slug: "west-lancashire", count: 937 },
  { name: "West Lindsey", slug: "west-lindsey", count: 884 },
  { name: "West Lothian", slug: "west-lothian", count: 1147 },
  { name: "West Northamptonshire", slug: "west-northamptonshire", count: 4058 },
  { name: "West Oxfordshire", slug: "west-oxfordshire", count: 1133 },
  { name: "West Suffolk", slug: "west-suffolk", count: 1655 },
  { name: "Westminster", slug: "westminster", count: 5712 },
  { name: "Westmorland and Furness", slug: "westmorland-and-furness", count: 3091 },
  { name: "Wigan", slug: "wigan", count: 2582 },
  { name: "Wiltshire", slug: "wiltshire", count: 4215 },
  { name: "Winchester City", slug: "winchester-city", count: 1184 },
  { name: "Windsor and Maidenhead", slug: "windsor-and-maidenhead", count: 1628 },
  { name: "Wirral", slug: "wirral", count: 2314 },
  { name: "Woking", slug: "woking", count: 779 },
  { name: "Wokingham", slug: "wokingham", count: 1120 },
  { name: "Wolverhampton", slug: "wolverhampton", count: 2156 },
  { name: "Worcester City", slug: "worcester-city", count: 830 },
  { name: "Worthing", slug: "worthing", count: 1017 },
  { name: "Wrexham", slug: "wrexham", count: 1207 },
  { name: "Wychavon", slug: "wychavon", count: 1097 },
  { name: "Wyre", slug: "wyre", count: 1031 },
  { name: "Wyre Forest", slug: "wyre-forest", count: 752 },
  { name: "York", slug: "york", count: 2176 },
];

const BY_SLUG = new Map(LOCAL_AUTHORITIES.map((a) => [a.slug, a]));
const BY_NAME = new Map(LOCAL_AUTHORITIES.map((a) => [a.name, a]));

export function getLocalAuthorityBySlug(slug: string): LocalAuthority | null {
  return BY_SLUG.get(slug) ?? null;
}

// Reverse lookup for internal linking from an establishment's raw localAuthorityName
// (e.g. its breadcrumb) back to its /area/[slug] landing page. Returns null for the
// handful of low-count authorities excluded from this list entirely (see file header).
export function getLocalAuthorityByName(name: string): LocalAuthority | null {
  return BY_NAME.get(name) ?? null;
}
