// Generated reference data: maps every local authority name (see local-authorities.ts)
// to its UK nation, derived from the same ONS boundary dataset used for the
// Compare areas choropleth (public/boundaries/uk-local-authorities.geojson) — see that
// file's own prep-script comment for how the ONS/FSA name differences were reconciled.
// Used to roll rankings up by nation and to identify London boroughs' peers for
// /food-hygiene-map's area rankings.
export type Nation = "England" | "Wales" | "Scotland" | "Northern Ireland";

export const LOCAL_AUTHORITY_NATION: Record<string, Nation> = {
  "Aberdeen City": "Scotland",
  "Aberdeenshire": "Scotland",
  "Adur": "England",
  "Amber Valley": "England",
  "Anglesey": "Wales",
  "Angus": "Scotland",
  "Antrim and Newtownabbey": "Northern Ireland",
  "Ards and North Down": "Northern Ireland",
  "Argyll and Bute": "Scotland",
  "Armagh City, Banbridge and Craigavon": "Northern Ireland",
  "Arun": "England",
  "Ashfield": "England",
  "Ashford": "England",
  "Babergh": "England",
  "Barking and Dagenham": "England",
  "Barnet": "England",
  "Barnsley": "England",
  "Basildon": "England",
  "Basingstoke and Deane": "England",
  "Bassetlaw": "England",
  "Bath and North East Somerset": "England",
  "Bedford": "England",
  "Belfast City": "Northern Ireland",
  "Bexley": "England",
  "Birmingham": "England",
  "Blaby": "England",
  "Blackburn": "England",
  "Blackpool": "England",
  "Blaenau Gwent": "Wales",
  "Bolsover": "England",
  "Bolton": "England",
  "Boston": "England",
  "Bournemouth, Christchurch and Poole": "England",
  "Bracknell Forest": "England",
  "Bradford": "England",
  "Braintree": "England",
  "Breckland": "England",
  "Brent": "England",
  "Brentwood": "England",
  "Bridgend": "Wales",
  "Brighton and Hove": "England",
  "Bristol": "England",
  "Broadland": "England",
  "Bromley": "England",
  "Bromsgrove": "England",
  "Broxbourne": "England",
  "Broxtowe": "England",
  "Buckinghamshire": "England",
  "Burnley": "England",
  "Bury": "England",
  "Caerphilly": "Wales",
  "Calderdale": "England",
  "Cambridge City": "England",
  "Camden": "England",
  "Cannock Chase": "England",
  "Canterbury City": "England",
  "Cardiff": "Wales",
  "Carmarthenshire": "Wales",
  "Castle Point": "England",
  "Causeway Coast and Glens": "Northern Ireland",
  "Central Bedfordshire": "England",
  "Ceredigion": "Wales",
  "Charnwood": "England",
  "Chelmsford": "England",
  "Cheltenham": "England",
  "Cherwell": "England",
  "Cheshire East": "England",
  "Cheshire West and Chester": "England",
  "Chesterfield": "England",
  "Chichester": "England",
  "Chorley": "England",
  "City of London Corporation": "England",
  "Clackmannanshire": "Scotland",
  "Colchester": "England",
  "Comhairle nan Eilean Siar (Western Isles)": "Scotland",
  "Conwy": "Wales",
  "Cornwall": "England",
  "Cotswold": "England",
  "Coventry": "England",
  "Crawley": "England",
  "Croydon": "England",
  "Cumberland": "England",
  "Dacorum": "England",
  "Darlington": "England",
  "Dartford": "England",
  "Denbighshire": "Wales",
  "Derby City": "England",
  "Derbyshire Dales": "England",
  "Derry City and Strabane": "Northern Ireland",
  "Doncaster": "England",
  "Dorset": "England",
  "Dover": "England",
  "Dudley": "England",
  "Dumfries and Galloway": "Scotland",
  "Dundee City": "Scotland",
  "Durham": "England",
  "Ealing": "England",
  "East Ayrshire": "Scotland",
  "East Cambridgeshire": "England",
  "East Devon": "England",
  "East Dunbartonshire": "Scotland",
  "East Hampshire": "England",
  "East Hertfordshire": "England",
  "East Lindsey": "England",
  "East Lothian": "Scotland",
  "East Renfrewshire": "Scotland",
  "East Riding of Yorkshire": "England",
  "East Staffordshire": "England",
  "East Suffolk": "England",
  "Eastbourne": "England",
  "Eastleigh": "England",
  "Edinburgh (City of)": "Scotland",
  "Elmbridge": "England",
  "Enfield": "England",
  "Epping Forest": "England",
  "Epsom and Ewell": "England",
  "Erewash": "England",
  "Exeter City": "England",
  "Falkirk": "Scotland",
  "Fareham": "England",
  "Fenland": "England",
  "Fermanagh and Omagh": "Northern Ireland",
  "Fife": "Scotland",
  "Flintshire": "Wales",
  "Folkestone and Hythe": "England",
  "Forest of Dean": "England",
  "Fylde": "England",
  "Gateshead": "England",
  "Gedling": "England",
  "Glasgow City": "Scotland",
  "Gloucester City": "England",
  "Gosport": "England",
  "Gravesham": "England",
  "Great Yarmouth": "England",
  "Greenwich": "England",
  "Guildford": "England",
  "Gwynedd": "Wales",
  "Hackney": "England",
  "Halton": "England",
  "Hammersmith and Fulham": "England",
  "Harborough": "England",
  "Haringey": "England",
  "Harlow": "England",
  "Harrow": "England",
  "Hart": "England",
  "Hartlepool": "England",
  "Hastings": "England",
  "Havant": "England",
  "Havering": "England",
  "Herefordshire": "England",
  "Hertsmere": "England",
  "High Peak": "England",
  "Highland": "Scotland",
  "Hillingdon": "England",
  "Hinckley and Bosworth": "England",
  "Horsham": "England",
  "Hounslow": "England",
  "Hull City": "England",
  "Huntingdonshire": "England",
  "Hyndburn": "England",
  "Inverclyde": "Scotland",
  "Ipswich": "England",
  "Isle of Wight": "England",
  "Isles of Scilly": "England",
  "Islington": "England",
  "Kensington and Chelsea": "England",
  "King's Lynn and West Norfolk": "England",
  "Kingston-Upon-Thames": "England",
  "Kirklees": "England",
  "Knowsley": "England",
  "Lambeth": "England",
  "Lancaster City": "England",
  "Leeds": "England",
  "Leicester City": "England",
  "Lewes": "England",
  "Lewisham": "England",
  "Lichfield": "England",
  "Lincoln City": "England",
  "Lisburn and Castlereagh City": "Northern Ireland",
  "Liverpool": "England",
  "Luton": "England",
  "Maidstone": "England",
  "Maldon": "England",
  "Malvern Hills": "England",
  "Manchester": "England",
  "Mansfield": "England",
  "Medway": "England",
  "Melton": "England",
  "Merthyr Tydfil": "Wales",
  "Merton": "England",
  "Mid Devon": "England",
  "Mid Suffolk": "England",
  "Mid Sussex": "England",
  "Mid Ulster": "Northern Ireland",
  "Mid and East Antrim": "Northern Ireland",
  "Middlesbrough": "England",
  "Midlothian": "Scotland",
  "Milton Keynes": "England",
  "Mole Valley": "England",
  "Monmouthshire": "Wales",
  "Moray": "Scotland",
  "Neath Port Talbot": "Wales",
  "New Forest": "England",
  "Newark and Sherwood": "England",
  "Newcastle Upon Tyne": "England",
  "Newcastle-Under-Lyme": "England",
  "Newham": "England",
  "Newport": "Wales",
  "Newry, Mourne and Down": "Northern Ireland",
  "North Ayrshire": "Scotland",
  "North Devon": "England",
  "North East Derbyshire": "England",
  "North East Lincolnshire": "England",
  "North Hertfordshire": "England",
  "North Kesteven": "England",
  "North Lanarkshire": "Scotland",
  "North Lincolnshire": "England",
  "North Norfolk": "England",
  "North Northamptonshire": "England",
  "North Somerset": "England",
  "North Tyneside": "England",
  "North Warwickshire": "England",
  "North West Leicestershire": "England",
  "North Yorkshire": "England",
  "Northumberland": "England",
  "Norwich City": "England",
  "Nottingham City": "England",
  "Nuneaton and Bedworth": "England",
  "Oadby and Wigston": "England",
  "Oldham": "England",
  "Orkney Islands": "Scotland",
  "Oxford City": "England",
  "Pembrokeshire": "Wales",
  "Pendle": "England",
  "Perth and Kinross": "Scotland",
  "Peterborough City": "England",
  "Plymouth City": "England",
  "Portsmouth": "England",
  "Powys": "Wales",
  "Preston": "England",
  "Reading": "England",
  "Redbridge": "England",
  "Redcar and Cleveland": "England",
  "Redditch": "England",
  "Reigate and Banstead": "England",
  "Renfrewshire": "Scotland",
  "Rhondda Cynon Taf": "Wales",
  "Ribble Valley": "England",
  "Richmond-Upon-Thames": "England",
  "Rochdale": "England",
  "Rochford": "England",
  "Rossendale": "England",
  "Rother": "England",
  "Rotherham": "England",
  "Rugby": "England",
  "Runnymede": "England",
  "Rushcliffe": "England",
  "Rushmoor": "England",
  "Rutland": "England",
  "Salford": "England",
  "Sandwell": "England",
  "Scottish Borders": "Scotland",
  "Sefton": "England",
  "Sevenoaks": "England",
  "Sheffield": "England",
  "Shetland Islands": "Scotland",
  "Shropshire": "England",
  "Slough": "England",
  "Solihull": "England",
  "Somerset": "England",
  "South Ayrshire": "Scotland",
  "South Cambridgeshire": "England",
  "South Derbyshire": "England",
  "South Gloucestershire": "England",
  "South Hams": "England",
  "South Holland": "England",
  "South Kesteven": "England",
  "South Lanarkshire": "Scotland",
  "South Norfolk": "England",
  "South Oxfordshire": "England",
  "South Ribble": "England",
  "South Staffordshire": "England",
  "South Tyneside": "England",
  "Southampton": "England",
  "Southend-On-Sea": "England",
  "Southwark": "England",
  "Spelthorne": "England",
  "St Albans City": "England",
  "St Helens": "England",
  "Stafford": "England",
  "Staffordshire Moorlands": "England",
  "Stevenage": "England",
  "Stirling": "Scotland",
  "Stockport": "England",
  "Stockton On Tees": "England",
  "Stoke-On-Trent": "England",
  "Stratford-on-Avon": "England",
  "Stroud": "England",
  "Sunderland": "England",
  "Surrey Heath": "England",
  "Sutton": "England",
  "Swale": "England",
  "Swansea": "Wales",
  "Swindon": "England",
  "Tameside": "England",
  "Tamworth": "England",
  "Tandridge": "England",
  "Teignbridge": "England",
  "Telford and Wrekin Council": "England",
  "Tendring": "England",
  "Test Valley": "England",
  "Tewkesbury": "England",
  "Thanet": "England",
  "Three Rivers": "England",
  "Thurrock": "England",
  "Tonbridge and Malling": "England",
  "Torbay": "England",
  "Torfaen": "Wales",
  "Torridge": "England",
  "Tower Hamlets": "England",
  "Trafford": "England",
  "Tunbridge Wells": "England",
  "Uttlesford": "England",
  "Vale of Glamorgan": "Wales",
  "Vale of White Horse": "England",
  "Wakefield": "England",
  "Walsall": "England",
  "Waltham Forest": "England",
  "Wandsworth": "England",
  "Warrington": "England",
  "Warwick": "England",
  "Watford": "England",
  "Waverley": "England",
  "Wealden": "England",
  "Welwyn Hatfield": "England",
  "West Berkshire": "England",
  "West Devon": "England",
  "West Dunbartonshire": "Scotland",
  "West Lancashire": "England",
  "West Lindsey": "England",
  "West Lothian": "Scotland",
  "West Northamptonshire": "England",
  "West Oxfordshire": "England",
  "West Suffolk": "England",
  "Westminster": "England",
  "Westmorland and Furness": "England",
  "Wigan": "England",
  "Wiltshire": "England",
  "Winchester City": "England",
  "Windsor and Maidenhead": "England",
  "Wirral": "England",
  "Woking": "England",
  "Wokingham": "England",
  "Wolverhampton": "England",
  "Worcester City": "England",
  "Worthing": "England",
  "Wrexham": "Wales",
  "Wychavon": "England",
  "Wyre": "England",
  "Wyre Forest": "England",
  "York": "England",
};

export function getNation(localAuthorityName: string): Nation | null {
  return LOCAL_AUTHORITY_NATION[localAuthorityName] ?? null;
}
